my_app/models.py
from datetime import datetime

from my_app import db
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash


class User(db.Model, UserMixin):
    # __table__ = db.Model.metadata.tables['user']

    __tablename__ = "user"
    user_id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.Text, unique=True, nullable=False)
    first_name = db.Column(db.Text, nullable=False)
    last_name = db.Column(db.Text, nullable=False)
    email = db.Column(db.Text, unique=True, nullable=False)
    password = db.Column(db.Text, nullable=False)
    questions = db.relationship('Question', backref=db.backref('user'))
    #answers = db.relationship('Answer', backref='user')

    def __repr__(self):
        return f"{self.user_id} {self.username} {self.first_name} {self.last_name} {self.email} {self.password}"

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    def get_id(self):
        return (self.user_id)


class Question(db.Model):
    # __table__ = db.Model.metadata.tables['question']

    __tablename__ = "question"
    question_id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.Text, nullable=False)
    content = db.Column(db.Text, nullable=False)
    create_time = db.Column(db.DateTime, default=datetime.now)
    question_user_id = db.Column(db.Integer, db.ForeignKey('user.user_id'), nullable=False)
    question_author = db.Column(db.Text)
    #answer_question_id = db.relationship('Question', backref='question')

    def __repr__(self):
        return '<Question %r>' % self.title


class Answer(db.Model):
    __tablename__ = "answer"
    answer_id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.Text, nullable=False)
    create_time = db.Column(db.DateTime, default=datetime.now)
    question_id = db.Column(db.Integer, db.ForeignKey('question.question_id'))
    answer_user_id = db.Column(db.Integer, db.ForeignKey('user.user_id'))
    answer_author = db.Column(db.Text)

    question = db.relationship('Question', backref='answers')
    author = db.relationship('User', backref='answers')

my_app/__init__.py
from flask import Flask
from flask.helpers import get_root_path
from flask_wtf.csrf import CSRFProtect
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager, login_required
import dash
import dash_bootstrap_components as dbc

db = SQLAlchemy()
csrf = CSRFProtect()
csrf._exempt_views.add('dash.dash.dispatch')
login_manager = LoginManager()


def create_app(config_class_name):
    """
    Initialise the Flask application.
    :rtype: Returns a configured Flask object
    """
    app = Flask(__name__)
    app.config.from_object(config_class_name)
    csrf.init_app(app)
    db.init_app(app)
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)
    register_dashapp(app)

    with app.app_context():
        #db.Model.metadata.reflect(bind=db.engine)
        from my_app.models import User, Question, Answer
        db.create_all()

    from my_app.auth.routes import auth_bp
    app.register_blueprint(auth_bp)

    from my_app.main.routes import main_bp
    app.register_blueprint(main_bp)

    return app


def register_dashapp(app):
    from my_app.cw1_app import layout
    from my_app.cw1_app.callbacks import register_callbacks

    meta_viewport = {"name": "viewport", "content": "width=device-width, initial-scale=1, shrink-to-fit=no"}

    dashapp = dash.Dash(__name__,
                         server=app,
                         url_base_pathname='/dashboard/',
                         assets_folder=get_root_path(__name__) + '/dashboard/assets/',
                         meta_tags=[meta_viewport],
                         #external_stylesheets=[dbc.themes.SKETCHY])
                         external_stylesheets=[dbc.themes.MINTY])

    with app.app_context():
        dashapp.title = 'Dashboard'
        dashapp.layout = layout.layout
        register_callbacks(dashapp)

    _protect_dash_views(dashapp)


def _protect_dash_views(dash_app):
    for view_func in dash_app.server.view_functions:
        if view_func.startswith(dash_app.config.routes_pathname_prefix):
            dash_app.server.view_functions[view_func] = login_required(dash_app.server.view_functions[view_func])

my_app/app.py
from my_app import create_app
from my_app.config import DevelopmentConfig

app = create_app(DevelopmentConfig)


@app.route('/')
def hello_world():
    return 'Hello World!'


if __name__ == '__main__':
    app.run(debug=True)

my_app/main/routes.py
from flask_login import current_user
from flask import Blueprint, render_template, flash, request, redirect, url_for
from flask_login import login_required
from sqlalchemy import or_
from my_app import db
from my_app.auth.forms import QuestionForm, AnswerForm
from my_app.models import Question, Answer

main_bp = Blueprint('main', __name__)


@main_bp.route('/')
def index():
    question = Question.query.order_by(db.text('-question_id')).all()
    return render_template('index.html', question=question)


@main_bp.route('/post_question', methods=['POST', 'GET'])
@login_required
def post_question():
    question_form = QuestionForm()
    if question_form.validate_on_submit():
        title = question_form.title.data
        content = question_form.content.data
        question = Question(title=title, content=content, question_user_id=current_user.user_id,
                            question_author=current_user.username)
        db.session.add(question)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('post_question.html')


@main_bp.route('/question/<int:question_id>', methods=['POST', 'GET'])
@login_required
def post_detail(question_id):
    question = Question.query.get(question_id)
    return render_template('post_detail.html', question=question)


@main_bp.route('/answer/<int:question_id>', methods=['POST', 'GET'])
@login_required
def answer(question_id):
    answer_form = AnswerForm()
    if answer_form.validate_on_submit():
        content = answer_form.content.data
        ans = Answer(content=content, question_id=question_id, answer_user_id=current_user.user_id,
                     answer_author=current_user.username)
        db.session.add(ans)
        db.session.commit()
        return redirect(url_for('main.post_detail', question_id=question_id))
    else:
        flash('Fail to comment!')
        return redirect(url_for('main.post_detail', question_id=question_id))

@main_bp.route('/search')
def search():
    # /search?q=xxx
    q = request.args.get('q')
    question = Question.query.filter(or_(Question.title.contains(q), Question.content.contains(q)))
    return render_template('index.html', question=question)

my_app/templates/_formhelpers.html
{% macro render_field(field) %}
    <div class="form-group">
        <dt>{{ field.label }}
            <dd>{{ field(**kwargs)|safe }}
                {% if field.errors %}
                    <ul class=errors>
                        {% for error in field.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </dd>
    </div>
{% endmacro %}

my_app/templates/index.html
{% extends 'layout.html' %}
{% block title %}Posts{% endblock %}
{% block head %}
    <link rel="stylesheet" href="https://fastly.jsdelivr.net/npm/@bootcss/v3.bootcss.com@1.0.35/examples/navbar/navbar.css">
{% endblock %}
{% block content %}
    <div class="row" style="margin-top: 20px;">
        <div class="col"></div>
        <div class="col-8" style="background-color: #fff; padding: 20px;">
            <h2>Welcome to use</h2><hr>
            <ul class="question-ul">
                {% for question in question %}
                    <li>
                        <div class="row">
                            <div class="col-1">
                                <img class="side-question-avatar" src="{{ url_for('static',filename='img/x.jpg') }}"
                                     alt="" style="width:50px;height:50px;">
                            </div>
                            <div class="col">
                                <div style="font-size:30px" class="question-title"><a href="{{ url_for('main.post_detail',
                                question_id=question.question_id) }}">{{ question.title }}</a>
                                </div>
                                <div class="question-detail">
                                    <span class="question-author">{{ question.question_author }}</span>
                                    <span class="question-time">{{ question.create_time }}</span>
                                    <br><br>
                                </div>
                                <div class="question-content" style="text-align: justify">{{ question.content }}</div>
                                <hr><br>
                            </div>
                            <div class="col-1"></div>

                        </div>

                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}

my_app/templates/layout.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="https://moodle.ucl.ac.uk/theme/styles.php/adaptable/1642686014_1642639754/all">


    {# Add to the head section #}
    <title>{{ title }}</title>
</head>
<body>

<header>
    {% include 'navbar.html' %}
</header>

<main>

    {# Displays flashed messages on a page #}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}

    <div class="container">
        {% block content %}{% endblock %}
    </div>
</main>

<script src="https://moodle.ucl.ac.uk/lib/javascript.php/1642638750/lib/polyfills/polyfill.js" defer></script>
</body>
</html>

my_app/templates/login.html
{% extends 'layout.html' %}
{% block content %}
    <form method="POST" action="{{ url_for('auth.login') }}">
        {{ form.csrf_token }}
        {{ form.email.label }} {{ form.email() }} <br>
        {{ form.password.label }} {{ form.password() }} <br><br>
        {{ form.remember() }} {{ form.remember.label }} <br>

        <br><br>
        <input type="submit" class="btn btn-primary" value="Sign in">

        {# Display the form validation errors #}
        {% for field, errors in form.errors.items() %}
            <div class="alert alert-error">
                {{ form[field].label }}: {{ ', '.join(errors) }}
            </div>
        {% endfor %}

    </form>
{% endblock %}

my_app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('main.index') }}">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.post_question') }}">PostTopics</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/dashboard/">Dashboard</a>
                </li>
                <li class="nav-item ml-2">
                    <form class="form-inline my-2 my-lg-0" method="GET" action="{{ url_for('main.search') }}">
                       <input class="form-control mr-sm-2" type="search" placeholder="Keyword" aria-label="Search" name="q">
                        <button class="btn btn-primary my-2 my-sm-0" type="submit">Search</button>
                    </form>

                </li>
                {% if current_user.is_anonymous %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.signup') }}">Sign up</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" style="text-align: right" href="{{ url_for('auth.logout') }}">Logout</a>
                    </li>
                {% endif %}


            </ul>
        </div>
    </div>
</nav>

my_app/templates/post_detail.html
{% extends 'layout.html' %}
{% block title %}{{ question.title }}{% endblock %}
{% block head %}
    <link rel="stylesheet" href="https://moodle.ucl.ac.uk/theme/styles.php/adaptable/1642686014_1642639754/all">
{% endblock %}
{% block content %}
    <div class="row" style="margin-top: 20px;">
        <div class="col"></div>
        <div class="col-8" style="background-color: #fff; padding: 20px;">
            <h2 class="page-title">{{ question.title }} </h2>
            <div class="question-info">
                <span>{{ question.question_author }}</span><br>
                <span>{{ question.create_time }}</span>
            </div>
            <hr>
            <div class="question-content">{{ question.content }}</div>
            <hr>
            <h5>Comments({{ question.answers|length }}):</h5>
            <form action="{{ url_for('main.answer', question_id=question.question_id) }}" method="post">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                <div>
                    <textarea type="text" rows="4" cols="80" placeholder="Add your comments here"
                              name="content"></textarea><br>
                    <button class="btn btn-secondary" style="text-align: right">Comment</button>
                </div>
                <hr>
            </form>
            <ul>
                {% for answer in question.answers %}
                    <li>
                        <div>

                            <div class="row">
                                <div class="col-1">
                                    <img class="side-question-avatar" src="{{ url_for('static',filename='img/x.jpg') }}"
                             alt="" style="width:30px;height:30px;">
                                </div>
                                <div class="col-8" style="text-align: left;font-size: large;">
                                    <span>{{ answer.author.username }}</span><br>
                                </div><br>
                                <div class="col"></div>
                            </div>
                            <div style="font-size: x-small">
                                <span>{{ answer.create_time }}</span><br>
                            </div>

                        </div>
                        <p>{{ answer.content }}</p><hr>
                </li>
                {% endfor %}
            </ul>


        </div>
        <div class="col"></div>
    </div>
{% endblock %}

my_app/templates/post_question.html
{% extends 'layout.html' %}
{% block head %}Post Question{% endblock %}
{% block content %}
<div class="row" style="margin-top: 20px;">
<div class="col"></div>
<div class="col-8">
    <h1 style="text-align: center;">Post Question</h1>
    <form action="{{ url_for('main.post_question') }}" method="POST">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <div class="form-group">
            <input type="text" name="title" class="form-control" placeholder="Please add a subject">
        </div>
        <div class="form-group">
            <textarea name="content" class="form-control" rows="10" placeholder="Please enter contents"></textarea>
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Submit">
        </div>
    </form>
</div>
<div class="col"></div>
</div>
{% endblock %}

my_app/templates/signup.html
{% extends 'layout.html' %}
{% block content %}
    <div class="row mt-6">
        <div class="col"></div>
        <div class="col-6">
            <form method="POST" action="{{ url_for('auth.signup') }}">
                {{ form.csrf_token }}
                {{ form.username.label }} <br> {{ form.username() }} <br>
                {{ form.first_name.label }} <br> {{ form.first_name() }} <br>
                {{ form.last_name.label }} <br> {{ form.last_name() }} <br>
                {{ form.email.label }} <br> {{ form.email() }} <br>
                {{ form.password.label }} <br> {{ form.password() }} <br>
                {{ form.password_repeat.label }} <br> {{ form.password_repeat() }} <br><br>
                <input type="submit" class="btn btn-primary btn-lg btn-block" value="Sign up">


                {# Display the form validation errors #}
                {% for field, errors in form.errors.items() %}
                    <div class="alert alert-error">
                        {{ form[field].label }}: {{ ', '.join(errors) }}
                    </div>
                {% endfor %}

            </form>

        </div>
        <div class="col"></div>
    </div>

{% endblock %}